{{- if and .Values.enabled (or (not .Values.service.headless) (not (empty .Values.volumeClaimTemplates))) }}
{{- if and .Values.service.nodePort (not (has .Values.service.type (list "NodePort" "LoadBalancer"))) }}
{{- fail (printf "You defined a nodePort, but service.type is '%s'. It must be 'NodePort' or 'LoadBalancer'." .Values.service.type) }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ cat  (include "kamuchart.fullname" .) "-service" | nospace }}
  labels:
    {{- include "kamuchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name | default "http" }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "kamuchart.selectorLabels" . | nindent 4 }}
{{- end }}
