{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ cat  (include "kamuchart.fullname" .) "-service" | nospace }}
  labels:
    {{- include "kamuchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless}}
  clusterIP: None
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "kamuchart.selectorLabels" . | nindent 4 }}
{{- end }}
